# -*- coding: utf-8 -*-
"""Cond_pref.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1-z58rx9uaaXY1-hSkSq55NfnDZoCIY
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Titre de l'application
st.title("Dashboard - Conditions Préférentielles des Clients")

# 1. Charger les données
uploaded_file = st.file_uploader("Téléchargez le fichier Excel", type=["xlsx"])
if uploaded_file:
    df = pd.read_excel(uploaded_file)

    st.subheader("Aperçu des données")
    st.dataframe(df)

    # 2. Vision Client
    st.subheader("🎯 Vision Client")
    client_id = st.selectbox("Sélectionnez un client", df['Client_ID'].unique())
    st.write(df[df['Client_ID'] == client_id])

    # 3. Vision Code Opération
    st.subheader("🔄 Vision par Code Opération")
    op_counts = df['Code_Operation'].value_counts().reset_index()
    op_counts.columns = ['Code Opération', 'Nombre de Conditions']
    fig_op = px.bar(op_counts, x='Code Opération', y='Nombre de Conditions', title="Répartition par Code Opération")
    st.plotly_chart(fig_op)

    # 4. Vision Agence
    st.subheader("🏢 Vision par Agence")
    agence_counts = df.groupby('Code_Agence')['Client_ID'].nunique().reset_index()
    agence_counts.columns = ['Code Agence', 'Nombre de Clients']
    fig_ag = px.bar(agence_counts, x='Code Agence', y='Nombre de Clients', title="Nombre de Clients par Agence")
    st.plotly_chart(fig_ag)

    # 5. Tableau interactif avec filtres
    st.subheader("🔍 Filtres dynamiques")
    agence_filtre = st.multiselect("Filtrer par agence", options=df['Code_Agence'].unique())
    op_filtre = st.multiselect("Filtrer par opération", options=df['Code_Operation'].unique())

    df_filtré = df.copy()
    if agence_filtre:
        df_filtré = df_filtré[df_filtré['Code_Agence'].isin(agence_filtre)]
    if op_filtre:
        df_filtré = df_filtré[df_filtré['Code_Operation'].isin(op_filtre)]

    st.dataframe(df_filtré)

else:
    st.info("Veuillez charger un fichier Excel pour commencer.")



